#!/bin/sh
function initnssdb() {
	dir=`echo "$1" | cut -f2- -d:`
	echo 'spawn -noecho certutil -d '"$1"' -N
	for { set keepgoing 1 } { $keepgoing > 0 } {} {
		expect {
			eof { set keepgoing 0; exit}
			": " {sleep 1; send "'"$2"'\r"; exp_continue}
		}
	}' > "$dir"/expect-script
	env LANG=C expect -f "$dir"/expect-script > /dev/null 2> /dev/null
}
function run_certutil() {
	echo '
	set send_slow { 1 .001 }
	set send_human { .1 .3 1 .05 2 }
	spawn certutil '"$*"'
	for { set keepgoing 1 } { $keepgoing > 0 } {} {
		expect {
			"type keys"         {send -s "FAKE"; exp_continue}
			"ontinue"           {send -s "\r"; exp_continue}
			-ex "*"             {send -s "FAKE"; exp_continue}
			eof                 {set keepgoing 0; exit}
		}
	}' > "$dir"/expect-script
	env LANG=C expect -f "$dir"/expect-script > /dev/null 2> /dev/null
}
function run_dos2unix() {
	dos2unix "$@" 2>&1 | sed -e s,Unix,unix,g -e s,UNIX,unix,g
}
function run_unix2dos() {
	unix2dos "$@" 2>&1 | sed -e s,Unix,unix,g -e s,UNIX,unix,g
}
